#!/usr/bin/env python3
"""
Command line entry point for plantuml2drawio.
"""
import os
import sys

# Add the src directory to the Python path when used in development mode
sys.path.insert(0, os.path.abspath(os.path.dirname(os.path.dirname(__file__))))

from src.plantuml2drawio.core import main

if __name__ == "__main__":
    main()
